#  k8s/api-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-backend
  template:
    metadata:
      labels:
        app: api-backend
    spec:
      imagePullSecrets:
        - name: acr-secret

      containers:
        - name: api-container
          image: mindxregistryhai01.azurecr.io/my-api-image:v8
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"

          # --- THÊM PHẦN CẤU HÌNH BIẾN MÔI TRƯỜNG VÀ KHẮC PHỤC SSL TẠI ĐÂY ---
          env:
            - name: MOCK_AUTH_ENABLED
              value: "true"
            # 2. CẤU HÌNH MINDX SSO
            - name: OAUTH_TOKEN_URL
              value: "https://id-dev.mindx.edu.vn/token" # Endpoint để đổi Token
            - name: OAUTH_USERINFO_URL
              value: "https://id-dev.mindx.edu.vn/me" # Endpoint lấy thông tin User
            - name: OAUTH_CLIENT_ID
              value: "mindx-onboarding"
            - name: OAUTH_CLIENT_SECRET
              # ĐIỀN CHÍNH XÁC SECRET CỦA BẠN VÀO ĐÂY (Nên dùng Secret/ConfigMap)
              value: "cHJldmVudGJvdW5kYmF0dHJlZWV4cGxvcmVjZWxsbmVydm91c3ZhcG9ydGhhbnN0ZWU="
            - name: OAUTH_CALLBACK_URL
              # BẮT BUỘC PHẢI KHỚP 100% VỚI LINK BẠN DÙNG ĐỂ REDIRECT
              value: "https://haimindx-app-djamcah4c6b0fyb3.z03.azurefd.net/callback"

            # 3. CÁC BIẾN CẦN THIẾT KHÁC (JWT, DB)
            - name: JWT_SECRET
              value: "super_secret_key_123"
            - name: MONGO_URI
              value: "mongodb+srv://gtvvjetnam_db_user:wDJMtlkvnwtFX6AA@mindxweek1.c0dp0am.mongodb.net/?appName=mindxweek1"
          # -------------------------------------------------------------------

          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          # ----------------------------------------
